// @vitest-environment jsdom
import { describe, it, expect, vi } from 'vitest'
import { screen, fireEvent, waitFor, act } from '@testing-library/react'
import { renderUi, makeFakeApi } from './helpers.jsx'
import { SettingsPage } from '../../../src/renderer/pages/SettingsPage.jsx'
import { DEFAULT_SETTINGS } from '../../../src/main/settings.js'

describe('SettingsPage', () => {
  it('changes every setting through onSettings', async () => {
    const onSettings = vi.fn()
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={onSettings} />)
    fireEvent.change(screen.getByLabelText('Jezik'), { target: { value: 'en' } })
    expect(onSettings).toHaveBeenLastCalledWith({ language: 'en' })
    fireEvent.click(screen.getByLabelText('Automatsko praćenje gledanja'))
    expect(onSettings).toHaveBeenLastCalledWith({ autoTrack: false })
    fireEvent.change(screen.getByLabelText('Epizoda je odgledana posle (%)'), { target: { value: '90' } })
    expect(onSettings).toHaveBeenLastCalledWith({ watchedThreshold: 90 })
    fireEvent.click(screen.getByLabelText('Pitaj pri zatvaranju plejera (umesto praga)'))
    expect(onSettings).toHaveBeenLastCalledWith({ askOnClose: true })
    fireEvent.change(screen.getByLabelText('Kvalitet'), { target: { value: '720' } })
    expect(onSettings).toHaveBeenLastCalledWith({ quality: '720' })
    fireEvent.change(screen.getByLabelText('Audio'), { target: { value: 'dub' } })
    expect(onSettings).toHaveBeenLastCalledWith({ mode: 'dub' })
    fireEvent.click(screen.getByLabelText('Automatsko ažuriranje ani-cli i yt-dlp'))
    expect(onSettings).toHaveBeenLastCalledWith({ autoUpdateTools: false })
  })
  it('has an About section that opens the repo', async () => {
    const api = makeFakeApi()
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={() => {}} updateState={{ status: 'disabled', currentVersion: '0.4.0' }} />, { api })
    expect(screen.getByRole('heading', { name: 'O aplikaciji' })).toBeInTheDocument()
    expect(screen.getByText('Verzija 0.4.0')).toBeInTheDocument()
    expect(screen.getByText('Napravio: Leqora')).toBeInTheDocument()
    expect(screen.getByText('© 2026 Leqora')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'GitHub' }))
    expect(api.app.openRepo).toHaveBeenCalled()
  })
  it('picks and clears the download folder', async () => {
    const onSettings = vi.fn()
    const api = makeFakeApi({ dialog: { pickFolder: vi.fn(async () => 'D:\\Anime') } })
    const { rerender } = renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={onSettings} />, { api })
    expect(screen.getByText('Nije postavljen (pita svaki put)')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Promeni' }))
    await waitFor(() => expect(onSettings).toHaveBeenCalledWith({ downloadDir: 'D:\\Anime' }))
  })
  it('shows tool versions and checks for updates', async () => {
    const api = makeFakeApi({ tools: { status: vi.fn(async () => ({ 'ani-cli': { installed: true, version: 'v5.1' } })) } })
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={() => {}} />, { api })
    await waitFor(() => expect(screen.getByText(/v5\.1/)).toBeInTheDocument())
    fireEvent.click(screen.getByRole('button', { name: 'Proveri ažuriranja alata' }))
    await waitFor(() => expect(api.tools.checkUpdates).toHaveBeenCalled())
  })
  it('edits profile name, sounds and animations', async () => {
    const onSettings = vi.fn()
    const onTestSound = vi.fn()
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS, systemName: 'nikola' }} onSettings={onSettings} onTestSound={onTestSound} />)
    const name = screen.getByLabelText('Ime na profilu')
    expect(name).toHaveAttribute('placeholder', 'nikola')
    fireEvent.change(name, { target: { value: '  Nikola L  ' } })
    fireEvent.blur(name)
    expect(onSettings).toHaveBeenLastCalledWith({ profileName: 'Nikola L' })
    fireEvent.click(screen.getByLabelText('Ključni zvuci (level up, završena serija, preuzimanje)'))
    expect(onSettings).toHaveBeenLastCalledWith({ soundKey: false })
    fireEvent.click(screen.getByLabelText('Zvuci interfejsa (klikovi, prelazi)'))
    expect(onSettings).toHaveBeenLastCalledWith({ soundUi: true })
    fireEvent.change(screen.getByLabelText('Jačina zvuka'), { target: { value: '25' } })
    expect(onSettings).toHaveBeenLastCalledWith({ soundVolume: 25 })
    fireEvent.click(screen.getByLabelText('Animacije'))
    expect(onSettings).toHaveBeenLastCalledWith({ animations: false })
    fireEvent.click(screen.getByRole('button', { name: /Probaj/ }))
    expect(onTestSound).toHaveBeenCalled()
  })
  it('clears the profile name back to the Windows name', () => {
    const onSettings = vi.fn()
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS, profileName: 'Nikola' }} onSettings={onSettings} />)
    const name = screen.getByLabelText('Ime na profilu')
    fireEvent.change(name, { target: { value: '' } })
    fireEvent.blur(name)
    expect(onSettings).toHaveBeenLastCalledWith({ profileName: null })
  })
  it('has a player section that saves each option', () => {
    const onSettings = vi.fn()
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={onSettings} updateState={{ status: 'disabled', currentVersion: '0.5.0' }} />)
    expect(screen.getByRole('heading', { name: 'Plejer' })).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Gde se pušta epizoda'), { target: { value: 'external' } })
    expect(onSettings).toHaveBeenLastCalledWith({ playerMode: 'external' })
    fireEvent.click(screen.getByLabelText('Automatski preskački uvod i odjavnu špicu'))
    expect(onSettings).toHaveBeenLastCalledWith({ autoSkip: true })
    fireEvent.click(screen.getByLabelText('Automatski pusti sledeću epizodu'))
    expect(onSettings).toHaveBeenLastCalledWith({ autoNext: false })
    fireEvent.click(screen.getByLabelText('Moderan izgled mpv-a (uosc)'))
    expect(onSettings).toHaveBeenLastCalledWith({ mpvModernUi: false })
  })
  it('has a subtitle section with a live preview', () => {
    vi.useFakeTimers()
    try {
      const onSettings = vi.fn()
      renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={onSettings} updateState={{ status: 'disabled', currentVersion: '0.6.1' }} />)
      expect(screen.getByRole('heading', { name: 'Titlovi' })).toBeInTheDocument()
      fireEvent.click(screen.getByLabelText('Titl za dub epizode'))
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: { enabled: { dub: true } } })
      fireEvent.change(screen.getByLabelText('Font'), { target: { value: 'georgia' } })
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: { font: 'georgia' } })
      fireEvent.change(screen.getByLabelText('Boja teksta'), { target: { value: 'yellow' } })
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: { color: 'yellow' } })
      fireEvent.click(screen.getByLabelText('Tamni okvir oko titla'))
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: { box: false } })
      onSettings.mockClear()
      const preview = document.querySelector('.subs-preview .subs')
      expect(preview).toHaveTextContent('Ovo je primer titla')
      fireEvent.change(screen.getByLabelText('Veličina titla'), { target: { value: '80' } })
      fireEvent.change(screen.getByLabelText('Veličina titla'), { target: { value: '90' } })
      expect(preview.style.getPropertyValue('--sub-size')).toBe('7.45cqh')
      expect(screen.getByText('90 %')).toBeInTheDocument()
      expect(onSettings).not.toHaveBeenCalled()
      act(() => vi.advanceTimersByTime(250))
      expect(onSettings).toHaveBeenCalledTimes(1)
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: { size: 90 } })
      fireEvent.change(screen.getByLabelText('Razmak između redova'), { target: { value: '0' } })
      act(() => vi.advanceTimersByTime(250))
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: { lineSpacing: 0 } })
      fireEvent.click(screen.getByRole('button', { name: 'Vrati podrazumevano' }))
      expect(onSettings).toHaveBeenLastCalledWith({ subtitles: DEFAULT_SETTINGS.subtitles })
    } finally { vi.useRealTimers() }
  })
  it('disables the box opacity when the box is off', () => {
    renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS, subtitles: { ...DEFAULT_SETTINGS.subtitles, box: false } }} onSettings={() => {}} />)
    expect(screen.getByLabelText('Zatamnjenost okvira')).toBeDisabled()
  })
  it('shows the update section and checks for updates', async () => {
    const onSettings = vi.fn()
    const { api } = renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={onSettings} updateState={{ status: 'none', currentVersion: '0.3.0', version: null, lastCheckedAt: '2026-10-02T10:00:00Z' }} />)
    expect(screen.getByText('Verzija 0.3.0')).toBeInTheDocument()
    expect(screen.getByText('Imaš najnoviju verziju')).toBeInTheDocument()
    expect(screen.getByText(/Poslednja provera:/)).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Proveri ažuriranja' }))
    expect(api.update.check).toHaveBeenCalled()
    fireEvent.click(screen.getByLabelText('Automatski preuzimaj ažuriranja'))
    expect(onSettings).toHaveBeenLastCalledWith({ autoDownloadUpdates: false })
  })
  it('explains updates are disabled outside the installed app and reports failures', () => {
    const { rerender } = renderUi(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={() => {}} updateState={{ status: 'disabled', currentVersion: '0.3.0' }} />)
    expect(screen.getByText('Ažuriranja rade samo u instaliranoj aplikaciji')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Proveri ažuriranja' })).not.toBeInTheDocument()
    rerender(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={() => {}} updateState={{ status: 'error', currentVersion: '0.3.0', error: 'x' }} />)
    expect(screen.getByText('Provera nije uspela')).toBeInTheDocument()
    rerender(<SettingsPage settings={{ ...DEFAULT_SETTINGS }} onSettings={() => {}} updateState={{ status: 'checking', currentVersion: '0.3.0' }} />)
    expect(screen.getByRole('button', { name: 'Proveravam…' })).toBeDisabled()
  })
})
